import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Auth0Provider  } from '@auth0/nextjs-auth0';
import Navigation from '@/components/layouts/Navigation';
import { ThemeProvider } from "@/contexts/ThemeContext";
import Footer from "@/components/layouts/Footer";
import CustomBackground from "@/components/layouts/CustomBackground";
import { auth0 } from "@/lib/auth0"
import { Toaster } from 'react-hot-toast';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession()

  return (
    <html lang="en">
      <Auth0Provider user={session?.user}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
          <ThemeProvider> 
            <CustomBackground>
              <Navigation />
              <main className="flex flex-col flex-grow justify-center">
                {children}
              </main>
              <Toaster position="bottom-right"/>
            </CustomBackground>
          </ThemeProvider>
          <Footer />
        </body>
      </Auth0Provider>
    </html>
  );
}
